name: tfbs
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - meme=5.5.7             # Includes FIMO
  - bedtools=2.31.1
  - pybigwig=0.3.24
  - pyranges=0.0.129       # Genomic range joins
  - numpy
  - pandas
  - matplotlib
  - jupyterlab
  - scikit-learn           # Train/test split + ML
  - ucsc-bigwigtobedgraph # Required for signal extraction tools
  - pip
  - pip:
      - seaborn            # Plotting
