name: tfbs
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - meme=5.5.7             # Includes FIMO
  - bedtools=2.31.1
  - pybigwig=0.3.24
  - numpy
  - pandas
  - jupyterlab
  - matplotlib
  - pip
  - pip:
      - seaborn    